### PR TITLE
Fix(Menu): Scope open menu to Current Window only

### LINKED ISSUE #606: Window menu sync cause menu to open in all instances

### PR DESCRIPTION
**Pull request by manavbp**
Resolves #606
[WIP]

### CODE REVIEW

File: app/reducers/ui.js [hunk 1]
```diff
@@ -5,19 +5,76 @@ import initialAppState from './initialAppState';
...
+const addWindowtoUI = ( state, payload ) =>
+{
+    const targetWindowId = payload.windowId;
+    const getCurrentWindowState = state.windows;
+    const windowState = [ ...getCurrentWindowState ];
+    windowState.push( { windowId: targetWindowId, settingsMenuIsVisible: false } );
+    const newState = { ...state, windows: windowState };
+    return newState;
+};
+function ToggleMenu( state, payload, showMenu )
```
Comment (joshuef) [inline app/reducers/ui.js]: we dont capitalise here. That's reserved for classes.

File: app/reducers/ui.js [hunk 2]
```diff
@@ -5,19 +5,76 @@ import initialAppState from './initialAppState';
...
+    else
+    {
+        updatedWindow.settingsMenuIsVisible = false;
+    }
+    windowState[updatedWindowIndex] = updatedWindow;
+    const newState = { ...state, windows: windowState };
+    return newState;
+}
+
+const showSettingsMenu = ( state, payload ) =>
```
Comment (joshuef) [inline app/reducers/ui.js]: these two funcs, show/hide could be removed and the func called directly from the reducer.

File: __tests__/reducers/ui.spec.js [hunk 3]
```diff
@@ -31,12 +38,13 @@ describe( 'notification reducer', () =>
...
+                    { windows: [ { windowId: 1, settingsMenuIsVisible: true } ] },
                     {
-                        type : TYPES.HIDE_SETTINGS_MENU
+                        type    : TYPES.HIDE_SETTINGS_MENU,
+                        payload : { windowId: 1 }
                     }
                 )
-            ).toEqual( { settingsMenuIsVisible: false } );
+            ).toEqual( uiStateHide );
         } );
```
Comment (joshuef) [inline __tests__/reducers/ui.spec.js]: @manavbp we're missing tests for add/remove window here.

Also we need tests for the added actions too. 👍
