### PR TITLE
fix top padding based on OS specification

### LINKED ISSUE #586: [OSX] Leave padding top left for osx
## Prerequisites

Use MacOS

## Expected Behavior

Close/minimize icons should not overlap any UI.

## Current Behavior

https://www.dropbox.com/s/t4buvky59m27icq/Screenshot%202019-02-11%2014.43.56.jpg?dl=0

## Possible Solution

Use constant OS detection to add a class to tab bar to add more padding.

### PR DESCRIPTION
**Pull request by manavbp**
Resolves #586 
```
QA:
The easiest way to test this PR would be to:
-Initialize the browser on Mac OS
-And check if close/minimize icons do not overlap any UI.
(Similarly for windows)
```

### CODE REVIEW

File: app/components/TabBar/TabBar.jsx [hunk 1]
```diff
@@ -147,7 +148,7 @@ export default class TabBar extends Component {
 
     render() {
         return (
-            <div className={styles.container}>
+            <div className={ navigator.appVersion.indexOf("Mac")!=-1? styles.containerMac : styles.container}>
```
Comment (joshuef) [inline app/components/TabBar/TabBar.jsx]: We have the OS determined in the global constants, lets use this if we can 👍

File: app/components/TabBar/tabBar.css [hunk 2]
```diff
@@ -3,14 +3,28 @@
...
+    padding-right: 10px;
     background: rgba( 207, 208, 209, 1);
     z-index: 4;
     font-size: 1.4rem;
     -webkit-app-region: drag;
 }
 
+.containerMac
+{
+    flex: 0;
```
Comment (joshuef) [inline app/components/TabBar/tabBar.css]: Here, I _think_ the only thing needed is `padding-left: 100px`, the rest should not need to be defined if this is just an extra class added TO the current tabBar. (no top padding is needed to be honest).

File: app/components/TabBar/TabBar.jsx (hunk 1 above)
Comment (joshuef) [reply app/components/TabBar/TabBar.jsx]: So aye, here should be both `styles.container` and IF MAC `styles.containerMac`
