### PR TITLE
fix(resolution): External NRS resolution fix.

### LINKED ISSUE #1052: cycling through versions of a SAFE site unblocks external unversioned resources
Testing against `v0.15.2-RC2`.
1. Create SAFE site consisting only of the following `index.html`:
```
<html>
  <head>
    <title>All the testing of this SAFE Browser stuff</title>
    <meta content="">
    <style></style>
  </head>
  <body>
  <img src="safe://increment.version/1.jpg" height="200px" width="200px>">
  <img src="safe://increment.version/2.jpg" height="200px" width="200px>">
  <img src="safe://increment.version/3.jpg" height="200px" width="200px>">
  <img src="safe://increment.version/4.jpg" height="200px" width="200px>">
  <img src="safe://increment.version/5.jpg" height="200px" width="200px>">
  <p>This is some text to check the page.</p>
  </body>
</html>
```
Ie, the images are unversioned links.
2. Upload, images are blocked:
image
3. Click back on version selection button then forward again (to return to the same version page as previously).

Expected:
Images should still be blocked and not displayed.
Actual:
Images are displayed:
image

Site URL: safe://yetanother.testinprogress/

### PR DESCRIPTION
**Pull request by joshuef**
Properly blocks unversioned NRS sites loaded as resources on another page
fixes #1052

### CODE REVIEW

File: app/extensions/safe/manageAndModifyRequests.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const manageAndModifyRequests = ( store: Store ) => {
                 ( tab: { webContentsId: number; url: string } ) =>
                     tab.webContentsId === targetWebContentsId
             );
-
+            logger.info( 'ssssdadaddd', details.url );
```
Comment (bochaco) [inline app/extensions/safe/manageAndModifyRequests.ts]: Shall we put some meaningful log message?
